Compact Translation Framework: ctf::TranslationGrammar::Rule Class Reference
ctf::TranslationGrammar::Rule Class Reference
A single rule. Is identified by a starting nonterminal and two vectors of input and output symbols.
#include <translation_grammar.hpp>
Public Member Functions
Rule (const Symbol &nonterminal, const vector< Symbol > &input, const vector< Symbol > &output, const vector< set< size_t >> &attributeActions={})
Constructs a rule.
Rule (const Symbol &nonterminal, const vector< Symbol > &both)
Constructs a rule with same input and output with specified attribute actions.
~Rule ()=default
Symbol & nonterminal ()
const Symbol & nonterminal () const
vector< Symbol > & input ()
const vector< Symbol > & input () const
vector< Symbol > & output ()
const vector< Symbol > & output () const
vector< set< size_t > > & actions ()
const vector< set< size_t > > & actions () const
Protected Member Functions
void check_nonterminals ()
Checks if nonterminals are in same space in input and output strings.
size_t count_input_terminals () const
Counts input nonterminals.
void create_empty_actions ()
Creates empty actions for terminal attributes.
Protected Attributes
Symbol nonterminal_
Starting nonterminal for this rule.
vector< Symbol > input_
A vector of input symbols.
vector< Symbol > output_
A vector of output symbols.
vector< set< size_t > > attributeActions_
Attribute copying from input to output when applying this rule. Implicitly created to copy no attributes.
Friends
Comparison operators
Lexicographic comparison of the three elements of Rules. Nonterminals have the highest priority, then input.
Returns
True if the comparison is true. False otherwise.
bool operator< (const Rule &lhs, const Rule &rhs)
bool operator== (const Rule &lhs, const Rule &rhs)
bool operator!= (const Rule &lhs, const Rule &rhs)
bool operator> (const Rule &lhs, const Rule &rhs)
bool operator<= (const Rule &lhs, const Rule &rhs)
bool operator>= (const Rule &lhs, const Rule &rhs)
Detailed Description
A single rule. Is identified by a starting nonterminal and two vectors of input and output symbols.
Defines attribute actions during syntax analysis for input terminals. Rules with starting symbols that are not nonterminals may serve as special markers for TranslationControl subclasses.
Definition at line 32 of file translation_grammar.hpp.
Constructor & Destructor Documentation
ctf::TranslationGrammar::Rule::Rule (const Symbol & nonterminal, const vector< Symbol > & input, const vector< Symbol > & output, const vector< set< size_t >> & attributeActions = {}) inline
Constructs a rule.
Parameters
[in] nonterminal Starting symbol.
[in] input Vector of input symbols. The nonterminals must match output in their count and order.
[in] output Vector of output symbols. The nonterminals must match input in their count and order.
[in] attributeActions Destinations of token attributes for each terminal in the input. Implicitly no attribute actions take place. The numbers say which output symbols are the targets for each input token's attribute.
Definition at line 114 of file translation_grammar.hpp.
References attributeActions_, check_nonterminals(), count_input_terminals(), create_empty_actions(), input_, nonterminal_, output_, and ctf::Symbol::TERMINAL.
ctf::TranslationGrammar::Rule::Rule (const Symbol & nonterminal, const vector< Symbol > & both) inline
Constructs a rule with same input and output with specified attribute actions.
Parameters
[in] nonterminal Starting symbol.
[in] both Vector of input symbols and at the same time output symbols.
Attribute targets are created to match all terminals to themselves.
Definition at line 155 of file translation_grammar.hpp.
References ctf::Symbol::TERMINAL, and ~Rule().
ctf::TranslationGrammar::Rule::~Rule () default
Member Function Documentation
vector<set<size_t> >& ctf::TranslationGrammar::Rule::actions () inline
Definition at line 178 of file translation_grammar.hpp.
References attributeActions_.
const vector<set<size_t> >& ctf::TranslationGrammar::Rule::actions () const inline
Definition at line 179 of file translation_grammar.hpp.
References attributeActions_, input_, nonterminal_, operator<, and output_.
void ctf::TranslationGrammar::Rule::check_nonterminals () inline protected
Checks if nonterminals are in same space in input and output strings.
Definition at line 61 of file translation_grammar.hpp.
References ctf::Symbol::NONTERMINAL, ctf::Symbol::SPECIAL, and ctf::Symbol::TERMINAL.
size_t ctf::TranslationGrammar::Rule::count_input_terminals () const inline protected
Counts input nonterminals.
Definition at line 85 of file translation_grammar.hpp.
References ctf::Symbol::TERMINAL.
void ctf::TranslationGrammar::Rule::create_empty_actions () inline protected
Creates empty actions for terminal attributes.
Definition at line 96 of file translation_grammar.hpp.
References count_input_terminals().
vector<Symbol>& ctf::TranslationGrammar::Rule::input () inline
Definition at line 172 of file translation_grammar.hpp.
References input_.
const vector<Symbol>& ctf::TranslationGrammar::Rule::input () const inline
Definition at line 173 of file translation_grammar.hpp.
References input_.
Symbol& ctf::TranslationGrammar::Rule::nonterminal () inline
Definition at line 169 of file translation_grammar.hpp.
References nonterminal_.
const Symbol& ctf::TranslationGrammar::Rule::nonterminal () const inline
Definition at line 170 of file translation_grammar.hpp.
References nonterminal_.
vector<Symbol>& ctf::TranslationGrammar::Rule::output () inline
Definition at line 175 of file translation_grammar.hpp.
References output_.
const vector<Symbol>& ctf::TranslationGrammar::Rule::output () const inline
Definition at line 176 of file translation_grammar.hpp.
References output_.
Friends And Related Function Documentation
bool operator!= (const Rule & lhs, const Rule & rhs) friend
Definition at line 205 of file translation_grammar.hpp.
bool operator< (const Rule & lhs, const Rule & rhs) friend
Definition at line 188 of file translation_grammar.hpp.
bool operator<= (const Rule & lhs, const Rule & rhs) friend
Definition at line 211 of file translation_grammar.hpp.
bool operator== (const Rule & lhs, const Rule & rhs) friend
Definition at line 201 of file translation_grammar.hpp.
bool operator> (const Rule & lhs, const Rule & rhs) friend
Definition at line 208 of file translation_grammar.hpp.
bool operator>= (const Rule & lhs, const Rule & rhs) friend
Definition at line 214 of file translation_grammar.hpp.
Member Data Documentation
vector<set<size_t> > ctf::TranslationGrammar::Rule::attributeActions_ protected
Attribute copying from input to output when applying this rule. Implicitly created to copy no attributes.
Definition at line 56 of file translation_grammar.hpp.
vector<Symbol> ctf::TranslationGrammar::Rule::input_ protected
A vector of input symbols.
Definition at line 45 of file translation_grammar.hpp.
Symbol ctf::TranslationGrammar::Rule::nonterminal_ protected
Starting nonterminal for this rule.
A rule with a symbol other than nonterminal may serve as a special marker rule for TranslationControl subclasses.
Definition at line 40 of file translation_grammar.hpp.
vector<Symbol> ctf::TranslationGrammar::Rule::output_ protected
A vector of output symbols.
Definition at line 49 of file translation_grammar.hpp.
The documentation for this class was generated from the following file:
/mnt/d/Code/reon/lib/ctf/src/translation_grammar.hpp