Compact Translation Framework: ctf::Translation Class Reference
ctf::Translation Class Reference
Defines a translation. Can be used multiple times for different inputs and outputs.
#include <translation.hpp>
Public Member Functions
Translation (LexicalAnalyzer::token_function la, TranslationControl &tc, const TranslationGrammar &tg, OutputGenerator::output_function og)
Constructs Translation with given lexical analyzer, translation control, translation grammar and output generator.
Translation (LexicalAnalyzer::token_function la, const string &tcName, const TranslationGrammar &tg, OutputGenerator::output_function og)
Constructs Translation with given lexical analyzer, translation grammar and output generator. Translation control is constructed by name.
Translation (LexicalAnalyzer::token_function la, TranslationControl &tc, const TranslationGrammar &tg, OutputGenerator::output_function og, TranslationControl::error_function syntaxErrors)
Constructs Translation with given lexical analyzer, translation control, translation grammar and output generator. Custom error messages are given for syntax errors.
Translation (LexicalAnalyzer::token_function la, const string &tcName, const TranslationGrammar &tg, OutputGenerator::output_function og, TranslationControl::error_function syntaxErrors)
Constructs Translation with given lexical analyzer, translation grammar and output generator. Translation control is constructed by name. Custom error messages are given for syntax errors.
~Translation ()
void run (std::istream &input, std::ostream &output)
Translates input from istream and outputs the translation to ostream.
Static Public Member Functions
static std::unique_ptr< TranslationControl > control (const string &name)
Factory method for creating TranslationControl variants.
Protected Attributes
LexicalAnalyzer lexicalAnalyzer_
Provides input terminals from istream.
std::unique_ptr< TranslationControl > control_ = nullptr
Holds standard control when generated with Translation::control().
TranslationControl & translationControl_
Reference to TranslationControl to be used.
TranslationGrammar translationGrammar_
Translation grammar that defines accepted language and output language.
OutputGenerator outputGenerator_
Outputs output terminals to ostream.
Detailed Description
Defines a translation. Can be used multiple times for different inputs and outputs.
Definition at line 25 of file translation.hpp.
Constructor & Destructor Documentation
ctf::Translation::Translation (LexicalAnalyzer::token_function la, TranslationControl & tc, const TranslationGrammar & tg, OutputGenerator::output_function og) inline
Constructs Translation with given lexical analyzer, translation control, translation grammar and output generator.
Parameters
[in] la A callable to perform lexical analysis.
[in] tc A translation control to drive the translation.
[in] tg Translation grammar that defines the input and output languages. A copy is made.
[in] og A callable to perform output generation.
Definition at line 59 of file translation.hpp.
References ctf::TranslationControl::set_grammar(), and ctf::TranslationControl::set_lexical_analyzer().
ctf::Translation::Translation (LexicalAnalyzer::token_function la, const string & tcName, const TranslationGrammar & tg, OutputGenerator::output_function og) inline
Constructs Translation with given lexical analyzer, translation grammar and output generator. Translation control is constructed by name.
Parameters
[in] la A callable to perform lexical analysis.
[in] tcName Name of a built-in translation control.
[in] tg Translation grammar that defines the input and output languages.
[in] og A callable to perform output generation.
Definition at line 77 of file translation.hpp.
References ctf::TranslationControl::set_grammar(), and ctf::TranslationControl::set_lexical_analyzer().
ctf::Translation::Translation (LexicalAnalyzer::token_function la, TranslationControl & tc, const TranslationGrammar & tg, OutputGenerator::output_function og, TranslationControl::error_function syntaxErrors) inline
Constructs Translation with given lexical analyzer, translation control, translation grammar and output generator. Custom error messages are given for syntax errors.
Parameters
[in] la A callable to perform lexical analysis.
[in] tc A translation control to drive the translation.
[in] tg Translation grammar that defines the input and output languages.
[in] og A callable to perform output generation
[in] syntaxErrors A callable to provide syntax error messages.
Definition at line 97 of file translation.hpp.
References ctf::TranslationControl::set_syntax_error_message().
ctf::Translation::Translation (LexicalAnalyzer::token_function la, const string & tcName, const TranslationGrammar & tg, OutputGenerator::output_function og, TranslationControl::error_function syntaxErrors) inline
Constructs Translation with given lexical analyzer, translation grammar and output generator. Translation control is constructed by name. Custom error messages are given for syntax errors.
Parameters
[in] la A callable to perform lexical analysis.
[in] tcName Name of a built-in translation control.
[in] tg Translation grammar that defines the input and output languages.
[in] og A callable to perform output generation.
[in] syntaxErrors A callable to provide syntax error messages.
Definition at line 114 of file translation.hpp.
References ctf::TranslationControl::set_syntax_error_message().
ctf::Translation::~Translation () inline
Definition at line 120 of file translation.hpp.
Member Function Documentation
static std::unique_ptr<TranslationControl> ctf::Translation::control (const string & name) inline static
Factory method for creating TranslationControl variants.
Parameters
[in] name Name of built-in translation control. Viable options are: "ll".
Returns
A std::unique_ptr containing a new translation control.
Definition at line 146 of file translation.hpp.
void ctf::Translation::run (std::istream & input, std::ostream & output) inline
Translates input from istream and outputs the translation to ostream.
Parameters
[in] input Input stream.
[out] output Output stream.
Definition at line 127 of file translation.hpp.
References ctf::OutputGenerator::get_token(), ctf::TranslationControl::output(), ctf::TranslationControl::run(), ctf::LexicalAnalyzer::set_input(), and ctf::OutputGenerator::set_output().
Member Data Documentation
std::unique_ptr<TranslationControl> ctf::Translation::control_ = nullptr protected
Holds standard control when generated with Translation::control().
Definition at line 34 of file translation.hpp.
LexicalAnalyzer ctf::Translation::lexicalAnalyzer_ protected
Provides input terminals from istream.
Definition at line 30 of file translation.hpp.
OutputGenerator ctf::Translation::outputGenerator_ protected
Outputs output terminals to ostream.
Definition at line 47 of file translation.hpp.
TranslationControl& ctf::Translation::translationControl_ protected
Reference to TranslationControl to be used.
Definition at line 38 of file translation.hpp.
TranslationGrammar ctf::Translation::translationGrammar_ protected
Translation grammar that defines accepted language and output language.
Definition at line 43 of file translation.hpp.
The documentation for this class was generated from the following file:
/mnt/d/Code/reon/lib/ctf/src/translation.hpp