Compact Translation Framework: ctf::LLTranslationControl Class Reference
ctf::LLTranslationControl Class Reference
Implements LL top down translation control.
#include <ll_translation_control.hpp>
Public Types
using error_function = std::function< string(const Symbol &nonterminal, const Symbol &terminal)>
Error message getter function.
Public Member Functions
LLTranslationControl ()=default
Constructs a LLTranslationControl.
virtual ~LLTranslationControl ()=default
Default destructor.
LLTranslationControl (LexicalAnalyzer &la, TranslationGrammar &tg)
Constructs LLTranslationControl with a LexicalAnalyzer and TranslationGrammar.
virtual void set_grammar (const TranslationGrammar &tg)
Sets translation grammar.
virtual void run ()
Runs the translation. Output symbols are stored in output_.
virtual void set_lexical_analyzer (LexicalAnalyzer &la)
Sets lexical analyzer.
virtual void set_syntax_error_message (error_function f)
Sets syntax error message function.
virtual const tstack< Symbol > & output () const
Returns a constant reference to output symbols.
Protected Types
using Rule = TranslationGrammar::Rule
Alias for TranslationGrammar::Rule.
Protected Member Functions
void create_ll_table ()
void create_empty ()
Creates Empty set for each nonterminal.
void create_first ()
Creates First set for each nonterminal.
void create_follow ()
Creates Follow set for each nonterminal.
void create_predict ()
Creates Predict set for each nonterminal.
void create_attibute_actions (tstack< Symbol >::iterator obegin, const vector< set< size_t >> &targets, tstack< vector< tstack< Symbol >::iterator >> &attributeActions)
Creates iterator attribute actions for incoming terminals.
virtual Symbol next_token ()
Returns the next token obtained from lexicalAnalyzer_.
Protected Attributes
vector< bool > empty_
Empty set for each nonterminal.
vector< vector< Symbol > > first_
First set for each nonterminal.
vector< vector< Symbol > > follow_
Follow set for each nonterminal.
vector< vector< Symbol > > predict_
Predict set for each nonterminal.
LLTable llTable_
LL table used to control the translation.
LexicalAnalyzer * lexicalAnalyzer_ = nullptr
Lexical analyzer for getting tokens from input.
const TranslationGrammar * translationGrammar_ = nullptr
Translation grammar defining the input and output languages.
tstack< Symbol > input_
Tstack of input symbols.
tstack< Symbol > output_
Tstack of output symbols.
error_function syntaxErrorMessage_
Syntax error message function.
Detailed Description
Implements LL top down translation control.
Definition at line 16 of file ll_translation_control.hpp.
Member Typedef Documentation
using ctf::TranslationControl::error_function = std::function<string(const Symbol &nonterminal, const Symbol &terminal)> inherited
Error message getter function.
Definition at line 31 of file translation_control.hpp.
using ctf::TranslationControl::Rule = TranslationGrammar::Rule protected inherited
Alias for TranslationGrammar::Rule.
Definition at line 37 of file translation_control.hpp.
Constructor & Destructor Documentation
ctf::LLTranslationControl::LLTranslationControl () default
Constructs a LLTranslationControl.
virtual ctf::LLTranslationControl::~LLTranslationControl () virtual default
Default destructor.
ctf::LLTranslationControl::LLTranslationControl (LexicalAnalyzer & la, TranslationGrammar & tg) inline
Constructs LLTranslationControl with a LexicalAnalyzer and TranslationGrammar.
Parameters
[in] la A reference to the lexical analyzer to be used to get tokens.
[in] tg The translation grammar for this translation.
Definition at line 262 of file ll_translation_control.hpp.
References set_grammar(), and ctf::TranslationControl::set_lexical_analyzer().
Member Function Documentation
void ctf::LLTranslationControl::create_attibute_actions (tstack< Symbol >::iterator obegin, const vector< set< size_t >> & targets, tstack< vector< tstack< Symbol >::iterator >> & attributeActions) inline protected
Creates iterator attribute actions for incoming terminals.
Parameters
[in] obegin Iterator to the first Symbol of the output of the applied Rule.
[in] targets Indices of the target actions for all input terminals.
[out] attributeActions Targets to append incoming terminal's attributes.
Definition at line 231 of file ll_translation_control.hpp.
References LLTranslationControl(), ctf::tstack< T >::push(), ctf::reverse(), ctf::Symbol::TERMINAL, and ~LLTranslationControl().
void ctf::LLTranslationControl::create_empty () inline protected
Creates Empty set for each nonterminal.
Definition at line 55 of file ll_translation_control.hpp.
References ctf::Symbol::NONTERMINAL, ctf::TranslationGrammar::nonterminal_index(), ctf::TranslationGrammar::nonterminals(), ctf::TranslationGrammar::rules(), ctf::Symbol::TERMINAL, and ctf::TranslationControl::translationGrammar_.
void ctf::LLTranslationControl::create_first () inline protected
Creates First set for each nonterminal.
Definition at line 96 of file ll_translation_control.hpp.
References ctf::modify_set(), ctf::Symbol::NONTERMINAL, ctf::TranslationGrammar::nonterminal_index(), ctf::TranslationGrammar::nonterminals(), ctf::TranslationGrammar::rules(), ctf::Symbol::TERMINAL, and ctf::TranslationControl::translationGrammar_.
void ctf::LLTranslationControl::create_follow () inline protected
Creates Follow set for each nonterminal.
Definition at line 132 of file ll_translation_control.hpp.
References ctf::Symbol::eof(), ctf::modify_set(), ctf::Symbol::NONTERMINAL, ctf::TranslationGrammar::nonterminal_index(), ctf::TranslationGrammar::nonterminals(), ctf::reverse(), ctf::TranslationGrammar::rules(), ctf::TranslationGrammar::starting_symbol(), ctf::Symbol::TERMINAL, and ctf::TranslationControl::translationGrammar_.
void ctf::LLTranslationControl::create_ll_table () inline protected
Creates all sets and creates a new LL table.
Definition at line 43 of file ll_translation_control.hpp.
References create_empty(), create_first(), create_follow(), create_predict(), and ctf::TranslationControl::translationGrammar_.
void ctf::LLTranslationControl::create_predict () inline protected
Creates Predict set for each nonterminal.
Definition at line 190 of file ll_translation_control.hpp.
References ctf::modify_set(), ctf::Symbol::NONTERMINAL, ctf::TranslationGrammar::nonterminal_index(), ctf::reverse(), ctf::TranslationGrammar::rules(), ctf::Symbol::TERMINAL, and ctf::TranslationControl::translationGrammar_.
virtual Symbol ctf::TranslationControl::next_token () inline protected virtual inherited
Returns the next token obtained from lexicalAnalyzer_.
Definition at line 68 of file translation_control.hpp.
References ctf::LexicalAnalyzer::get_token().
virtual const tstack<Symbol>& ctf::TranslationControl::output () const inline virtual inherited
Returns a constant reference to output symbols.
Returns
All output symbols.
Definition at line 102 of file translation_control.hpp.
virtual void ctf::LLTranslationControl::run () inline virtual
Runs the translation. Output symbols are stored in output_.
Implements ctf::TranslationControl.
Definition at line 279 of file ll_translation_control.hpp.
References ctf::Symbol::attribute(), create_attibute_actions(), ctf::Symbol::eof(), ctf::TranslationControl::input_, ctf::TranslationControl::lexicalAnalyzer_, ctf::Symbol::name(), ctf::TranslationControl::next_token(), ctf::TranslationControl::output_, ctf::tstack< T >::pop(), ctf::LLTable::rule_index(), ctf::TranslationGrammar::rules(), ctf::TranslationGrammar::starting_symbol(), ctf::TranslationControl::syntaxErrorMessage_, ctf::TranslationControl::translationGrammar_, and ctf::Symbol::type().
virtual void ctf::LLTranslationControl::set_grammar (const TranslationGrammar & tg) inline virtual
Sets translation grammar.
Parameters
[in] tg The translation grammar for this translation.
Reimplemented from ctf::TranslationControl.
Definition at line 271 of file ll_translation_control.hpp.
References create_ll_table(), and ctf::TranslationControl::translationGrammar_.
virtual void ctf::TranslationControl::set_lexical_analyzer (LexicalAnalyzer & la) inline virtual inherited
Sets lexical analyzer.
Parameters
[in] la LexicalAnalyzer to be set.
Definition at line 77 of file translation_control.hpp.
virtual void ctf::TranslationControl::set_syntax_error_message (error_function f) inline virtual inherited
Sets syntax error message function.
Parameters
[in] f Callable to return syntax error strings.
Definition at line 91 of file translation_control.hpp.
Member Data Documentation
vector<bool> ctf::LLTranslationControl::empty_ protected
Empty set for each nonterminal.
Definition at line 21 of file ll_translation_control.hpp.
vector<vector<Symbol> > ctf::LLTranslationControl::first_ protected
First set for each nonterminal.
Definition at line 25 of file ll_translation_control.hpp.
vector<vector<Symbol> > ctf::LLTranslationControl::follow_ protected
Follow set for each nonterminal.
Definition at line 29 of file ll_translation_control.hpp.
tstack<Symbol> ctf::TranslationControl::input_ protected inherited
Tstack of input symbols.
Definition at line 50 of file translation_control.hpp.
LexicalAnalyzer* ctf::TranslationControl::lexicalAnalyzer_ = nullptr protected inherited
Lexical analyzer for getting tokens from input.
Definition at line 42 of file translation_control.hpp.
LLTable ctf::LLTranslationControl::llTable_ protected
LL table used to control the translation.
Definition at line 38 of file ll_translation_control.hpp.
tstack<Symbol> ctf::TranslationControl::output_ protected inherited
Tstack of output symbols.
Definition at line 54 of file translation_control.hpp.
vector<vector<Symbol> > ctf::LLTranslationControl::predict_ protected
Predict set for each nonterminal.
Definition at line 33 of file ll_translation_control.hpp.
error_function ctf::TranslationControl::syntaxErrorMessage_ protected inherited
Initial value:
= [](auto nt, auto t) {
    return "Nonterminal " + nt.name() + ", token " + t.name() +
           (t.attribute() == "" ? "" : "." + t.attribute());
  }
Syntax error message function.
Defaults to writing nonterminal's and token's names. Is bound to change.
Definition at line 60 of file translation_control.hpp.
const TranslationGrammar* ctf::TranslationControl::translationGrammar_ = nullptr protected inherited
Translation grammar defining the input and output languages.
Definition at line 46 of file translation_control.hpp.
The documentation for this class was generated from the following file:
/mnt/d/Code/reon/lib/ctf/src/ll_translation_control.hpp