Compact Translation Framework: ctf::OutputGenerator Class Reference
ctf::OutputGenerator Class Reference
#include <output_generator.hpp>
Public Types
using output_function = std::function< void(std::ostream &, const Symbol &)>
Alias for std::function.
Public Member Functions
OutputGenerator (output_function f=OutputGenerator::default_output)
Constructs OutputGenerator without an output stream.
OutputGenerator (std::ostream &_o, output_function f=OutputGenerator::default_output)
Constructs OutputGenerator with an output stream.
bool stream_set () const
Returns true if an output stream has been set.
void set_output (std::ostream &o)
Sets the output stream.
void get_token (const Symbol &t)
Outputs a token to the given stream.
Static Public Member Functions
static void default_output (std::ostream &os, const Symbol &t)
Default output function.
Detailed Description
Outputs tokens to output stream.
Definition at line 25 of file output_generator.hpp.
Member Typedef Documentation
using ctf::OutputGenerator::output_function = std::function<void(std::ostream &, const Symbol &)>
Alias for std::function.
Definition at line 30 of file output_generator.hpp.
Constructor & Destructor Documentation
ctf::OutputGenerator::OutputGenerator (output_function f = OutputGenerator::default_output) inline
Constructs OutputGenerator without an output stream.
Parameters
[in] f Callable to print incoming symbols to a stream. At the end of output, it will receive Symbol::eofI() and should reset itself.
Definition at line 49 of file output_generator.hpp.
ctf::OutputGenerator::OutputGenerator (std::ostream & _o, output_function f = OutputGenerator::default_output) inline
Constructs OutputGenerator with an output stream.
Parameters
[in] _o Output stream.
[in] f Callable to print incoming symbols to a stream. At the end of output, it will receive Symbol::eof() and should reset itself.
Definition at line 57 of file output_generator.hpp.
Member Function Documentation
static void ctf::OutputGenerator::default_output (std::ostream & os, const Symbol & t) inline static
Default output function.
Prints Symbol name and attribute.
Definition at line 86 of file output_generator.hpp.
References ctf::Symbol::attribute(), ctf::Symbol::eof(), and ctf::Symbol::name().
void ctf::OutputGenerator::get_token (const Symbol & t) inline
Outputs a token to the given stream.
Parameters
[in] t Symbol to be output. If t is equal to Symbol::eof(), outputFunction should reset itself.
If OutputGenerator::stream_set() is false, this results in undefined behavior.
Definition at line 79 of file output_generator.hpp.
void ctf::OutputGenerator::set_output (std::ostream & o) inline
Sets the output stream.
Parameters
[in] o Output stream.
Definition at line 70 of file output_generator.hpp.
bool ctf::OutputGenerator::stream_set () const inline
Returns true if an output stream has been set.
Returns
True if an output stream has been set. False otherwise.
Definition at line 65 of file output_generator.hpp.
The documentation for this class was generated from the following file:
/mnt/d/Code/reon/lib/ctf/src/output_generator.hpp