Compact Translation Framework: ctf::TranslationGrammar Class Reference
ctf::TranslationGrammar Class Reference
Translation grammar.
#include <translation_grammar.hpp>
Classes
class Rule
A single rule. Is identified by a starting nonterminal and two vectors of input and output symbols.
Public Member Functions
TranslationGrammar ()
Constructs an empty TranslationGrammar. Implicit starting symbol is "E"_nt.
TranslationGrammar (const vector< Rule > &rules, const Symbol &starting_symbol)
Constructs a TranslationGrammar, takes terminals and nonterminals from the rules' inputs and starting symbol.
TranslationGrammar (const vector< Symbol > &nonterminals, const vector< Symbol > &terminals, const vector< Rule > &rules, const Symbol &starting_symbol)
Constructs a TranslationGrammar.
~TranslationGrammar ()=default
vector< Symbol > & terminals ()
const vector< Symbol > & terminals () const
vector< Symbol > & nonterminals ()
const vector< Symbol > & nonterminals () const
vector< Rule > & rules ()
const vector< Rule > & rules () const
Symbol & starting_symbol ()
const Symbol & starting_symbol () const
size_t nonterminal_index (const Symbol &nt) const
Returns a nonterminal's index.
size_t terminal_index (const Symbol &t) const
Returns a terminal's index.
Static Public Member Functions
static const vector< Symbol > & EPSILON_STRING ()
Returns an empty string of symbols.
Protected Attributes
vector< Symbol > terminals_
A sorted set of all input terminals.
vector< Symbol > nonterminals_
A sorted set of all input nonterminals.
vector< Rule > rules_
An unsorted vector of all rules.
Symbol starting_symbol_
The starting symbol.
Detailed Description
Translation grammar.
Definition at line 22 of file translation_grammar.hpp.
Constructor & Destructor Documentation
ctf::TranslationGrammar::TranslationGrammar () inline
Constructs an empty TranslationGrammar. Implicit starting symbol is "E"_nt.
Definition at line 243 of file translation_grammar.hpp.
ctf::TranslationGrammar::TranslationGrammar (const vector< Rule > & rules, const Symbol & starting_symbol) inline
Constructs a TranslationGrammar, takes terminals and nonterminals from the rules' inputs and starting symbol.
Parameters
[in] rules A vector of rules. Duplicates will be erased, even with different atttribute actions.
[in] starting_symbol The starting symbol.
Definition at line 251 of file translation_grammar.hpp.
References ctf::make_set(), ctf::Symbol::NONTERMINAL, ctf::Symbol::TERMINAL, and ctf::Symbol::type().
ctf::TranslationGrammar::TranslationGrammar (const vector< Symbol > & nonterminals, const vector< Symbol > & terminals, const vector< Rule > & rules, const Symbol & starting_symbol) inline
Constructs a TranslationGrammar.
Parameters
[in] terminals A vector of all terminals. Duplicates will be erased.
[in] nonterminals A vector of all nonterminals. Duplicates will be erased.
[in] rules A vector of all rules. Duplicates will be erased, even with different atttribute actions.
[in] starting_symbol The starting symbol.
Checks rules for validity with supplied terminals and nonterminals.
Definition at line 290 of file translation_grammar.hpp.
References ctf::Symbol::eof(), ctf::is_in(), ctf::make_set(), ctf::Symbol::NONTERMINAL, ctf::Symbol::TERMINAL, ctf::Symbol::type(), and ~TranslationGrammar().
ctf::TranslationGrammar::~TranslationGrammar () default
Member Function Documentation
static const vector<Symbol>& ctf::TranslationGrammar::EPSILON_STRING () inline static
Returns an empty string of symbols.
Definition at line 353 of file translation_grammar.hpp.
size_t ctf::TranslationGrammar::nonterminal_index (const Symbol & nt) const inline
Returns a nonterminal's index.
Parameters
[in] nt Nonterminal Symbol to be searched.
Returns
The index of the nonterminal.
Undefined behavior if the nonterminal is not in nonterminals_.
Definition at line 377 of file translation_grammar.hpp.
vector<Symbol>& ctf::TranslationGrammar::nonterminals () inline
Definition at line 361 of file translation_grammar.hpp.
References nonterminals_.
const vector<Symbol>& ctf::TranslationGrammar::nonterminals () const inline
Definition at line 362 of file translation_grammar.hpp.
References nonterminals_.
vector<Rule>& ctf::TranslationGrammar::rules () inline
Definition at line 364 of file translation_grammar.hpp.
References rules_.
const vector<Rule>& ctf::TranslationGrammar::rules () const inline
Definition at line 365 of file translation_grammar.hpp.
References rules_.
Symbol& ctf::TranslationGrammar::starting_symbol () inline
Definition at line 367 of file translation_grammar.hpp.
References starting_symbol_.
const Symbol& ctf::TranslationGrammar::starting_symbol () const inline
Definition at line 368 of file translation_grammar.hpp.
References starting_symbol_.
size_t ctf::TranslationGrammar::terminal_index (const Symbol & t) const inline
Returns a terminal's index.
Parameters
[in] t Terminal Symbol to be searched.
Returns
The index of the terminal.
Undefined behavior if the terminal in not in terminals_.
Definition at line 388 of file translation_grammar.hpp.
vector<Symbol>& ctf::TranslationGrammar::terminals () inline
Definition at line 358 of file translation_grammar.hpp.
References terminals_.
const vector<Symbol>& ctf::TranslationGrammar::terminals () const inline
Definition at line 359 of file translation_grammar.hpp.
References terminals_.
Member Data Documentation
vector<Symbol> ctf::TranslationGrammar::nonterminals_ protected
A sorted set of all input nonterminals.
Definition at line 228 of file translation_grammar.hpp.
vector<Rule> ctf::TranslationGrammar::rules_ protected
An unsorted vector of all rules.
Definition at line 232 of file translation_grammar.hpp.
Symbol ctf::TranslationGrammar::starting_symbol_ protected
The starting symbol.
Definition at line 236 of file translation_grammar.hpp.
vector<Symbol> ctf::TranslationGrammar::terminals_ protected
A sorted set of all input terminals.
Definition at line 224 of file translation_grammar.hpp.
The documentation for this class was generated from the following file:
/mnt/d/Code/reon/lib/ctf/src/translation_grammar.hpp