Compact Translation Framework: ctf::LexicalAnalyzer Class Reference
ctf::LexicalAnalyzer Class Reference
Extracts tokens from input stream. Tokens can be Symbols of any type, type is to be ignored.
#include <lexical_analyzer.hpp>
Public Types
using token_function = std::function< Token(std::istream &)>
Alias to std::function.
Public Member Functions
LexicalAnalyzer (token_function f=LexicalAnalyzer::default_input)
Constructs LexicalAnalyzer without a given input stream. If specified, f determines the tokenFunction.
LexicalAnalyzer (std::istream &_i, token_function f=LexicalAnalyzer::default_input)
Constructs LexicalAnalyzer with a given istream. If specified, f determines the tokenFunction.
bool stream_set () const
Returns true when a stream has been set.
void set_input (std::istream &s)
Sets the input stream to a given stream.
Token get_token ()
Uses tokenFunction to get a Token from input stream. If LexicalAnalyzer::stream_set() is false, this results in undefined behavior.
Static Public Member Functions
static Token default_input (std::istream &is)
Default token extractor. All characters that are not spaces become tokens.
Detailed Description
Extracts tokens from input stream. Tokens can be Symbols of any type, type is to be ignored.
Lexical errors are created by creating a token with an unused name. Then, attribute should be used as an error message.
Definition at line 38 of file lexical_analyzer.hpp.
Member Typedef Documentation
using ctf::LexicalAnalyzer::token_function = std::function<Token(std::istream &)>
Alias to std::function.
Definition at line 43 of file lexical_analyzer.hpp.
Constructor & Destructor Documentation
ctf::LexicalAnalyzer::LexicalAnalyzer (token_function f = LexicalAnalyzer::default_input) inline
Constructs LexicalAnalyzer without a given input stream. If specified, f determines the tokenFunction.
Parameters
[in] f A callable for extracting Tokens from a stream.
Definition at line 64 of file lexical_analyzer.hpp.
ctf::LexicalAnalyzer::LexicalAnalyzer (std::istream & _i, token_function f = LexicalAnalyzer::default_input) inline
Constructs LexicalAnalyzer with a given istream. If specified, f determines the tokenFunction.
Parameters
[in] _i A stream from which tokens are extracted.
[in] f A callable for extracting Tokens from a stream.
Definition at line 72 of file lexical_analyzer.hpp.
Member Function Documentation
static Token ctf::LexicalAnalyzer::default_input (std::istream & is) inline static
Default token extractor. All characters that are not spaces become tokens.
Definition at line 103 of file lexical_analyzer.hpp.
References ctf::Symbol::eof(), and ctf::Terminal().
Token ctf::LexicalAnalyzer::get_token () inline
Uses tokenFunction to get a Token from input stream. If LexicalAnalyzer::stream_set() is false, this results in undefined behavior.
Returns
A token recieved from tokenFunction. Type UNKNOWN is changed to type TERMINAL.
Definition at line 92 of file lexical_analyzer.hpp.
References ctf::Symbol::attribute(), ctf::Symbol::name(), ctf::Symbol::TERMINAL, ctf::Symbol::type(), and ctf::Symbol::UNKNOWN.
void ctf::LexicalAnalyzer::set_input (std::istream & s) inline
Sets the input stream to a given stream.
Parameters
[in] s Stream to be set.
Definition at line 85 of file lexical_analyzer.hpp.
bool ctf::LexicalAnalyzer::stream_set () const inline
Returns true when a stream has been set.
Returns
True when a stream has been set. False otherwise.
Definition at line 80 of file lexical_analyzer.hpp.
The documentation for this class was generated from the following file:
/mnt/d/Code/reon/lib/ctf/src/lexical_analyzer.hpp