Compact Translation Framework: ctf::LLTable Class Reference
ctf::LLTable Class Reference
Class containing rule indices to be used in a LL controlled translation.
#include <ll_table.hpp>
Public Types
using cell = size_t
Type of the cells.
using row = vector< cell >
Type of the rows.
Public Member Functions
LLTable ()=default
Constructs an empty LL table.
LLTable (const TranslationGrammar &tg, const vector< vector< Symbol >> &predict)
Constructs a LLtable from a translation grammar and a predict set.
size_t rule_index (const Symbol &nt, const Symbol &t)
Returns an index of the rule to be used when t is the current token and nt is at the top of input stack.
Protected Attributes
vector< row > table_
Table storing rule indices.
map< Symbol, size_t > nonterminalMap_
Mapping nonterminals to indices to table_.
map< Symbol, size_t > terminalMap_
Mapping terminals to indices to table_ rows.
size_t invalidRuleIndex_
Stores invalid rule index.
Detailed Description
Class containing rule indices to be used in a LL controlled translation.
Definition at line 18 of file ll_table.hpp.
Member Typedef Documentation
using ctf::LLTable::cell = size_t
Type of the cells.
Definition at line 23 of file ll_table.hpp.
using ctf::LLTable::row = vector<cell>
Type of the rows.
Definition at line 27 of file ll_table.hpp.
Constructor & Destructor Documentation
ctf::LLTable::LLTable () default
Constructs an empty LL table.
ctf::LLTable::LLTable (const TranslationGrammar & tg, const vector< vector< Symbol >> & predict) inline
Constructs a LLtable from a translation grammar and a predict set.
Parameters
[in] tg TranslationGrammar. Terminals and Nonterminals are mapped to their indices. Rule indices are stored in LLTable.
[in] predict Predict set for table construction.
Definition at line 58 of file ll_table.hpp.
References ctf::Symbol::eof(), ctf::TranslationGrammar::nonterminals(), ctf::TranslationGrammar::rules(), and ctf::TranslationGrammar::terminals().
Member Function Documentation
size_t ctf::LLTable::rule_index (const Symbol & nt, const Symbol & t) inline
Returns an index of the rule to be used when t is the current token and nt is at the top of input stack.
Parameters
[in] nt Nonterminal on the top of the stack.
[in] t Last read terminal.
Returns
Index of the applicable rule.
If no rule is applicable, returns the index beyond the last rule.
Definition at line 104 of file ll_table.hpp.
Member Data Documentation
size_t ctf::LLTable::invalidRuleIndex_ protected
Stores invalid rule index.
Definition at line 45 of file ll_table.hpp.
map<Symbol, size_t> ctf::LLTable::nonterminalMap_ protected
Mapping nonterminals to indices to table_.
Definition at line 37 of file ll_table.hpp.
vector<row> ctf::LLTable::table_ protected
Table storing rule indices.
Definition at line 33 of file ll_table.hpp.
map<Symbol, size_t> ctf::LLTable::terminalMap_ protected
Mapping terminals to indices to table_ rows.
Definition at line 41 of file ll_table.hpp.
The documentation for this class was generated from the following file:
/mnt/d/Code/reon/lib/ctf/src/ll_table.hpp