Compact Translation Framework: ctf Namespace Reference
ctf Namespace Reference
Namespaces
literals
Classes
class const_reverser
class LexicalAnalyzer
Extracts tokens from input stream. Tokens can be Symbols of any type, type is to be ignored.
class LexicalError
Exception class to be thrown by user defined lexical analyzers on lexical errors.
class LLTable
Class containing rule indices to be used in a LL controlled translation.
class LLTranslationControl
Implements LL top down translation control.
class OutputGenerator
class reverser
class SemanticError
An exception class for semantic errors.
class Symbol
Symbol, may represent a Terminal, Nonterminal or end of input.
class SyntaxError
Exception class for syntax errors.
class Translation
Defines a translation. Can be used multiple times for different inputs and outputs.
class TranslationControl
Abstract class for syntax driven translation control.
class TranslationException
Base exception class for project specific exceptions.
class TranslationGrammar
Translation grammar.
class tstack
STL stack with added functionality. Iterators don't lose validity when manipulating with stack.
Typedefs
using Token = Symbol
Alias for Symbol. Token and Symbol are interchangable.
Functions
Symbol Terminal (const string &name, const string &attribute="")
Returns a Symbol with Type::Terminal, given name and attribute.
Symbol Nonterminal (const string &name)
Returns a Symbol with Type::Nonterminal, given name and attribute.
template<class T >
void make_set (T &container)
Makes contents of a container a set.
template<class T , class CT >
bool is_in (const CT &c, const T &e)
Element presence in a sorted container.
template<class T >
T set_union (const T &lhs, const T &rhs)
Set union of two sorted containers.
template<class CT >
bool modify_set (CT &target, const CT &addition)
Set union between sorted containers.
template<class T >
reverser< T > reverse (T &t)
Reverses a container.
template<class T >
const const_reverser< T > reverse (const T &t)
Reverses a const container.
template<class IT , class OT >
OT transform (const IT &it)
Constructs STL from different STL using iterators.
Typedef Documentation
using ctf::Token = typedef Symbol
Alias for Symbol. Token and Symbol are interchangable.
Definition at line 29 of file lexical_analyzer.hpp.
Function Documentation
template<class T , class CT > bool ctf::is_in (const CT & c, const T & e)
Element presence in a sorted container.
Returns
True if element e is contained in sorted container c. False otherwise.
Definition at line 308 of file generic_types.hpp.
template<class T > void ctf::make_set (T & container)
Makes contents of a container a set.
Parameters
[in,out] container Container to be made into a set.
Sorts the container and removes duplicates.
Definition at line 296 of file generic_types.hpp.
template<class CT > bool ctf::modify_set (CT & target, const CT & addition)
Set union between sorted containers.
Parameters
[in,out] target Targer container. One half of the resulting set. Must be sorted.
[in] addition One half of the resulting set. Must be sorted.
Returns
True if the set union between the two containers changed the target container. False otherwise.
Definition at line 334 of file generic_types.hpp.
References set_union().
Symbol ctf::Nonterminal (const string & name) inline
Returns a Symbol with Type::Nonterminal, given name and attribute.
Parameters
[in] name Name of returned symbol.
Returns
A Symbol with type Nonterminal and given name.
Definition at line 178 of file base.hpp.
References ctf::Symbol::NONTERMINAL.
template<class T > reverser<T> ctf::reverse (T & t)
Reverses a container.
Parameters
[in] t Container to be reversed.
Returns
Container reversing adapter.
Definition at line 398 of file generic_types.hpp.
template<class T > const const_reverser<T> ctf::reverse (const T & t)
Reverses a const container.
Parameters
[in] t Container to be reversed.
Returns
Container reversing adapter.
Definition at line 407 of file generic_types.hpp.
template<class T > T ctf::set_union (const T & lhs, const T & rhs)
Set union of two sorted containers.
Returns
A set union of the two containers.
Definition at line 318 of file generic_types.hpp.
Symbol ctf::Terminal (const string & name, const string & attribute = "") inline
Returns a Symbol with Type::Terminal, given name and attribute.
Parameters
[in] name Name of returned symbol.
[in] attribute Attribute of returned Symbol. Defaults to "".
Returns
A Symbol with type Terminal, given name and given attribute.
Definition at line 170 of file base.hpp.
References ctf::Symbol::TERMINAL.
template<class IT , class OT > OT ctf::transform (const IT & it)
Constructs STL from different STL using iterators.
Parameters
[in] it Container from which the target container is constructed.
Returns
A container with all elements of the first container.
Definition at line 417 of file generic_types.hpp.
References ctf::tstack< T >::begin(), and ctf::tstack< T >::end().